twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_4_layout.html.twig' ]
  globals:
    CheckIfUserService: '@App\Services\CheckIfUserService'
    CompanyDetailsService: '@App\Services\CompanyDetailsService'
    CountAllocatedWebsites: '@App\Services\CountAllocatedWebsites'
    CountBusinessContactsService: '@App\Services\CountBusinessContactsService'
    CountBusinessContactReferralsService: '@App\Services\CountBusinessContactReferralsService'
    CountPendingWebsiteInquiriesService: '@App\Services\CountPendingWebsiteInquiriesService'
    ImportUserService: '@App\Services\ImportUserService'
    LanguagesService: '@App\Services\LanguagesService'
    ProductService: '@App\Services\ProductService'
    TranslationsImportService: '@App\Services\TranslationsImportService'
    TranslationsWorkerService: '@App\Services\TranslationsWorkerService'
    WeatherService: '@App\Services\WeatherService'
    CountPhotos: '@App\Services\CountPhotos'
    PhotoAuthorsByLocation: '@App\Services\PhotoAuthorsByLocation'


when@test:
  twig:
    strict_variables: true

