  # This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

imports:
  - { resource: 'services_project_specific.yaml' }

parameters:
  business_contacts_map_icon_directory:      '%kernel.project_dir%/public/administration/ATSSharedFiles/BusinessContactsMapIcons/'
  language_icon_directory:                   '%kernel.project_dir%/public/administration/ATSSharedFiles/LanguageIcons/'
  import_templates_directory:                '%kernel.project_dir%/public/administration/ATSSharedFiles/_ImportTemplates/'
  business_contacts_attachments_directory:   '%kernel.project_dir%/public/administration/Attachments/BusinessContacts/Files/'
  business_contacts_photos_directory:        '%kernel.project_dir%/public/administration/Attachments/BusinessContacts/Photos/'
  cms_copy_attachments_directory:            '%kernel.project_dir%/public/administration/Attachments/CMSCopyAttachments/'
  cms_photos_directory:                      '%kernel.project_dir%/public/administration/Attachments/CMSPhotos/'
  favicons_directory: '%kernel.project_dir%/public/administration/Attachments/Favicons/'
  file_attachments_directory:                '%kernel.project_dir%/public/administration/Attachments/FileAttachments/'
  instructions_attachments_directory:        '%kernel.project_dir%/public/administration/Attachments/Instructions/'
  map_icons_import_directory:       '%kernel.project_dir%/public/administration/Import/MapIcons/'
  photos_directory:                          '%kernel.project_dir%/public/administration/Attachments/Photos/'
  user_attachments_directory:                '%kernel.project_dir%/public/administration/Attachments/Users/'
  user_photos_directory:                     'administration/Attachments/Users/Photos/'

  business_contacts_import_directory:        '%kernel.project_dir%/public/administration/Import/BusinessContacts/'
  business_types_import_directory:           '%kernel.project_dir%/public/administration/Import/BusinessTypes/'
  company_details_import_directory:          '%kernel.project_dir%/public/administration/Import/CompanyDetails/'
  cms_copy_page_formats_import_directory:    '%kernel.project_dir%/public/administration/Import/CmsCopyPageFormats/'
  cms_copy_import_directory:                 '%kernel.project_dir%/public/administration/Import/CmsCopy/'
  cms_photo_import_directory:                '%kernel.project_dir%/public/administration/Import/CmsPhotos/'
  competitors_import_directory:              '%kernel.project_dir%/public/administration/Import/Competitors/'
  facebook_groups_import_directory:          '%kernel.project_dir%/public/administration/Import/FacebookGroups/'
  facebook_groups_reviews_import_directory:  '%kernel.project_dir%/public/administration/Import/FacebookGroupsReviews/'
  languages_import_directory:                '%kernel.project_dir%/public/administration/Import/Languages/'
  product_import_directory:                  '%kernel.project_dir%/public/administration/Import/Products/'
  translations_import_directory:             '%kernel.project_dir%/public/administration/Import/Translations/'
  useful_links_import_directory:             '%kernel.project_dir%/public/administration/Import/UsefulLinks/'
  users_import_directory:                    '%kernel.project_dir%/public/administration/Import/Users/'

  public:                                    '%kernel.project_dir%/public/'


services:
  # Automatically wire and configure all services under App\Service
  App\Service\EmailFetcherService:
    arguments: []

  _defaults:
    autowire: true      # Automatically injects dependencies in your services
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  # Makes classes in src/ available to be used as services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  # Explicitly define SecurityAuthenticator service if autowiring fails
  App\Security\SecurityAuthenticator:
    autowire: true
    autoconfigure: true
    public: false

  # Explicitly define the AuthenticationEntryPoint service
  App\Security\AuthenticationEntryPoint:
    class: App\Security\AuthenticationEntryPoint
    arguments: []

  # Explicitly inject ContainerInterface as the service container
  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  # Explicitly define UserPasswordHasherInterface for password hashing
  Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface: '@security.user_password_hasher'

  # controllers are imported separately to make sure services can be injected as action arguments
  # even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  # Additional custom service definitions can go here
